// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./context/AppContext";
import dynamic from 'next/dynamic';
import FacebookPixelTracker from "./tools/FacebookPixelTracker";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Trendora || Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-slate-200 pb-5 antialiased`}>
        <AppProvider>
          {children}
        </AppProvider>
<FacebookPixelTracker />
      </body>
    </html>
  );
}
