import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./(components)/Footer";
import Float from "./(components)/Float";
import { AppProvider } from "./context/AppContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-slate-200 pb-5 antialiased`}>
        <AppProvider>
  
          {children}
        </AppProvider>

        {/* Correctly placed noscript fallback */}
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: 'none' }}
            src="https://www.facebook.com/tr?id=2128380290964389&ev=PageView&noscript=1"
          />
        </noscript>
      </body>
    </html>
  );
}

